<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
?>

<?php
$start = microtime(true);
$widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($viewModel->getJsonConfigurationHtmlEscaped());
//$widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['breadcrumbs']);
$breadcrumbs = $widget['breadcrumbs'];
$end = microtime(true);
//var_dump($end - $start);

if (false) {
?>
<script type="text/x-magento-init">
    {
        ".breadcrumbs": {
            "breadcrumbs": <?= /* @noEscape */ $widgetOptions ?>
        }
    }
</script>
<?php } ?>
<?php if (isset($breadcrumbs) && is_array($breadcrumbs)) : ?>
<div class="breadcrumbs">
    <ul class="items">
        <li class="item home">
            <a href="/"
               title="Home">
                 Home
            </a>
        </li>
        <?php foreach($breadcrumbs['categories'] as $cat) { ?>
            <?php //var_dump($cat); ?>
        <li class="item category-<?= $cat['id']?>">
            <a href="<?= $cat['url'];?>"
               title="<?= $cat['name']?>">
                 <?= $cat['name']?>
            </a>
        </li>
        <?php } ?>
        <li class="item category-last">
            <a href="<?= $breadcrumbs['lastCategoryUrl'];?>"
               title="<?= $breadcrumbs['lastCategoryName']?>">
                 <?= $breadcrumbs['lastCategoryName']?>
            </a>
        </li>
        <li class="item product">
        <strong><?= $block->escapeHtml($breadcrumbs['product']) ?></strong>
        </li>
    </ul>
</div>
<?php endif; ?>